#!/usr/bin/python3

"""Exercise 6"""


def raise_exception_msg(message=""):
    """Raise a name exception with a message"""
    raise NameError(message)
